jinchuika/app-suni

README.md

Branch de carlos

---

src/apps/main/views.py
src/apps/mye/views.py
src/apps/tpe/menus.py
src/apps/tpe/urls.py
src/apps/tpe/views.py
src/static/js/extrajs/index.js
src/static/js/extrajs/tpe.js
src/templates/tpe/calendario.html

- Ventanas emergentes en el calendario de inicio de TPE
- Calendario de TPE

Calendario de TPE

---

src/apps/kalite/api_views.py
src/apps/kardex/api_urls.py
src/apps/kardex/api_views.py
src/apps/kardex/forms.py
src/apps/kardex/menus.py
src/apps/kardex/models.py
src/apps/kardex/serializers.py
src/apps/kardex/urls.py
src/apps/kardex/views.py
src/apps/main/serializers.py
src/static/js/extrajs/kardex.js
src/templates/base/main-header.html
src/templates/kardex/entrada.html
src/templates/kardex/entrada_detail.html
src/templates/kardex/entrada_print.html
src/templates/kardex/equipo.html
src/templates/kardex/equipo_list.html
src/templates/kardex/informe.html
src/templates/kardex/proveedor_detail.html
src/templates/kardex/salida_detail.html
src/templates/kardex/salida_print.html

- Entradas del kardex con detalle
- Salidas del kardex con detalle
- Informe de existencias de kardex

Kardex (RC)

---

src/apps/tpe/urls.py
src/apps/tpe/views.py
src/templates/base/base-print.html
src/templates/kardex/proveedor_list.html
src/templates/tpe/ticket_detail.html
src/templates/tpe/ticket_entrega_print.html
src/templates/tpe/ticket_recepcion_print.html

Formularios de recepción / entrega para tickets de soporte

Mejoras al Kardex

---

src/apps/escuela/models.py
src/apps/escuela/views.py
src/apps/mye/api_urls.py
src/apps/mye/api_views.py
src/apps/mye/forms.py
src/apps/mye/models.py
src/apps/mye/serializers.py
src/apps/mye/views.py
src/static/js/extrajs/mye.js
src/templates/kalite/visita_form.html
src/templates/mye/solicitud_list.html

- Ahora el informe de solicitudes de MyE utiliza DRF como backend

Cambio al informe de solicitudes

---

src/apps/mye/api_urls.py
src/apps/mye/api_views.py
src/apps/mye/forms.py
src/apps/mye/serializers.py
src/apps/mye/views.py
src/apps/tpe/api_urls.py
src/apps/tpe/api_views.py
src/apps/tpe/menus.py
src/apps/tpe/serializers.py
src/apps/tpe/urls.py
src/apps/tpe/views.py
src/static/js/extrajs/mye.js
src/static/js/extrajs/tpe.js
src/templates/tpe/evaluacionmonitoreo_informe.html

- Se agregó un informe de evaluación de monitoreo
- El informe de Validaciones cambió para usar DRF

Informe de evaluación de monitoreo

---

src/apps/tpe/api_urls.py
src/apps/tpe/api_views.py
src/apps/tpe/forms.py
src/apps/tpe/menus.py
src/apps/tpe/serializers.py
src/apps/tpe/urls.py
src/apps/tpe/views.py
src/static/js/extrajs/tpe.js
src/templates/tpe/calendario.html
src/templates/tpe/dispositivo_reparacion_list.html

- Informe de dispositivos reparados
- Solucionado #87

Informe de dispositivos reparados. Fixes #87

---

src/apps/tpe/models.py
src/templates/tpe/garantia_detail.html
src/templates/tpe/ticket_detail.html
src/templates/tpe/ticket_reparacion_list.html

- Solucionado #85 
- Modificado el template de garantías para reflejar #89 
- Incluida la función de #90

Pequeña inclusión de mejoras

---

src/apps/kalite/api_views.py
src/apps/kalite/forms.py
src/apps/kalite/serializers.py
src/apps/kalite/urls.py
src/apps/kalite/views.py
src/apps/users/serializers.py
src/static/js/extrajs/kalite.js
src/templates/kalite/visita_informe.html

- **BETA** No está listo para implementación completa

Informe visitas de KA Lite (Beta)

---

src/apps/mye/api_urls.py
src/apps/mye/api_views.py
src/apps/mye/forms.py
src/apps/mye/models.py
src/apps/mye/serializers.py
src/apps/mye/urls.py
src/apps/mye/views.py
src/static/js/extrajs/mye.js
src/templates/mye/cooperante_list.html

- Nueva versión del informe de cooperantes
- Cambios al API de MyE

Nuevo informe de cooperantes (beta)

---

src/apps/mye/urls.py
src/apps/mye/views.py

- Se establecio el formato de URL  al archivo "url" de **mye**
- Se establecio la descripcion de cada vista en  el archivo "view" de **mye**

 Refactorización de archivos url y view

---

src/apps/mye/views.py

- Se agrego el comentario  de  solicitud mediante el  id de la escuela en  "url" de mye
- Se  corrigieron los errores en el estilo de documentación de todas las vistas en el  "view" de mye

Corrección de errores en el estilo de documentación

---

src/apps/main/serializers.py
src/apps/tpe/api_urls.py
src/apps/tpe/api_views.py
src/apps/tpe/forms.py
src/apps/tpe/models.py
src/apps/tpe/serializers.py
src/apps/tpe/urls.py
src/apps/tpe/views.py
src/static/js/extrajs/escuela.js
src/static/js/extrajs/tpe.js
src/templates/escuela/detail.html
src/templates/tpe/calendario.html
src/templates/tpe/visita_add.html
src/templates/tpe/visita_detail.html
src/templates/tpe/visita_list.html

- Creación de Api del Monitoreo de Visitas 
- Creación de Url para Api del Monitoreo de Visitas
- Integración del Api de Visitas al Calendario
- Integración de Filtros para las respectivas Vistas de Monitoreo de Visitas

Creacion de Api e integracion al caledario de vista de Visita

---

src/apps/naat/forms.py
src/apps/naat/menus.py
src/apps/naat/views.py
src/templates/naat/calendario.html
src/templates/naat/proceso_detail.html
src/templates/naat/sesionpresencial_detail.html

- Algunos formularios tenían los campos anteriores a la migración más reciente
- Faltaban algunos enlaces para las secciones de Naat

Correción de errores en Naat

---

src/apps/crm/forms.py
src/apps/crm/menus.py
src/apps/tpe/serializers.py
src/static/js/extrajs/tpe.js
src/templates/crm/contacto_add.html
src/templates/crm/correo_contacto_add.html
src/templates/crm/donante_detail.html
src/templates/crm/oferta_add.html
src/templates/crm/telefono_contacto_add.html

**CRM**
- Cambios  en permisos a usuarios
- Se agrego filtros  Para selección de usuarios
**TPE**
- Se agrego vínculos a los listados de monitoreo de visita
- Restructuración de serializer

Cambios Generales a Modulo CRM y TPE

---

src/apps/inventario/forms/__init__.py
src/apps/inventario/forms/software.py
src/apps/inventario/models.py
src/apps/inventario/urls/__init__.py
src/apps/inventario/urls/software.py
src/apps/inventario/views/__init__.py
src/apps/inventario/views/software.py
src/templates/inventario/software/software_add.html
src/templates/inventario/software/software_detail.html
src/templates/inventario/software/software_list.html
src/templates/inventario/software/versionsistema_add.html
src/templates/inventario/software/versionsistema_detail.html
src/templates/inventario/software/versionsistema_list.html

Creación del modulo de inventarios:
- Detalle de versión de sistema
- Listado de versiones de sistema
- Creación de versión del sistema
- Detalle de software
- Listado de software

Creando modulo de invetario

---

src/apps/inventario/forms/__init__.py
src/apps/inventario/forms/dispositivo.py
src/apps/inventario/forms/software.py
src/apps/inventario/signals.py
src/apps/inventario/urls/dispositivo.py
src/apps/inventario/urls/software.py
src/apps/inventario/views/dispositivo.py
src/apps/inventario/views/software.py
src/templates/inventario/Dispositivos/Teclados/teclado_detail.html
src/templates/inventario/Dispositivos/Teclados/teclado_form.html
src/templates/inventario/software/software_add.html
src/templates/inventario/software/versionsistema_add.html

Se crearon los  siguientes sub-modulos de inventario
- Edición de software
- Edición de versión de sistema
- Edición de teclados
- Detalle de teclados

Se Agrego el Uso de Triage como identificador

---

src/apps/crm/api_views.py
src/apps/crm/serializers.py
src/apps/tpe/serializers.py

Corrección de error en el serializer

Corrección de errores en serializer de TPE

---

src/apps/inventario/forms/dispositivo.py
src/apps/inventario/forms/salida.py
src/apps/inventario/urls/bodega.py
src/apps/inventario/urls/dispositivo.py
src/apps/inventario/urls/salida.py
src/apps/inventario/views/dispositivo.py
src/templates/inventario/dispositivo/solicitudmovimiento_add.html

- Creacion de solicitudes de movimiento
***

Solicitudes de Moviento

---

src/apps/conta/api_urls.py
src/apps/conta/api_views.py
src/apps/conta/forms.py
src/apps/conta/serializers.py
src/apps/conta/urls.py
src/apps/conta/views.py
src/apps/inventario/api_views/repuesto.py
src/apps/inventario/api_views/salida.py
src/apps/inventario/forms/salida.py
src/src/urls.py
src/static/js/extrajs/conta.js
src/templates/conta/periodo_add.html
src/templates/conta/periodo_detail.html
src/templates/conta/periodo_edit.html
src/templates/conta/periodo_list.html
src/templates/conta/precioestandar_add.html
src/templates/conta/precioestandar_list.html
src/templates/crm/donante_add.html
src/templates/inventario/repuesto/repuesto_list.html

- Se crearon vistas para contabilidad
- Se crearon urls de acceso para contabilidad
- Se crearon punto de acceso api-res  para contabilidad
- Se crearon template  para contabilidad
- Se crearon los archivos Javascript para contabilidad
- Se refactorizo codigo
- Se programo el reinventario
- Multiples validaciones
***

Se agrego el modulo de contabilidad, y refactorizacion de codigo

---

src/apps/conta/views.py

Se agrego url de redireccionamiento 

---

src/apps/conta/urls.py
src/apps/inventario/api_views/entrada.py
src/apps/inventario/forms/dispositivo.py
src/apps/inventario/forms/entrada.py
src/apps/inventario/models.py
src/apps/inventario/urls/dispositivo.py
src/apps/inventario/views/dispositivo.py
src/apps/inventario/views/entrada.py
src/apps/kalite/serializers.py
src/static/js/extrajs/inventario.js
src/static/js/extrajs/kalite.js
src/templates/inventario/dispositivo/ap/ap_detail.html
src/templates/inventario/dispositivo/ap/ap_edit.html
src/templates/kalite/visita_informe.html

- Mejoras Inventario (Entradas y Solicitudes de Movimiento) 
- Cambios en reporte de KaLite
***

Mejoras de Entradas y Cambios en reporte de KaLite

---

src/apps/inventario/views/dispositivo.py
src/apps/inventario/views/salida.py
src/static/js/extrajs/inventario.js
src/templates/inventario/dispositivo/solicitudmovimiento_update.html
src/templates/inventario/salida/paquetes_add.html
src/templates/inventario/salida/paquetes_detail.html

- Asignacion de scanner a movimiento de dispositivos
- Asignacion de scanner a salidas
- Correccion de codigo
***

Asignacion de scanner a salidas

---

src/static/js/extrajs/inventario.js
src/templates/inventario/repuesto/repuesto_detail.html

Cambios no subidos 

---

src/apps/conta/api_views.py
src/apps/conta/forms.py
src/apps/conta/views.py
src/apps/inventario/urls/desecho.py
src/apps/inventario/urls/salida.py
src/apps/inventario/views/desecho.py
src/apps/inventario/views/salida.py
src/templates/base/base.html
src/templates/inventario/desecho/desecho_print.html
src/templates/inventario/desecho/desechosalida_detail.html
src/templates/inventario/prestamo/prestamo_print.html
src/templates/inventario/salida/garantia_print.html
src/templates/inventario/salida/mineduc_print.html
src/templates/inventario/salida/salida_detail.html
src/templates/inventario/salida/salida_edit.html
src/templates/inventario/salida/tablet_print.html
src/templates/inventario/salida/tpe_print.html

- Creacion de Reportes de salida
- Actualizaciones al modulo de Contabilidad
***

Informes  de Salida y Actualizacion modulo Conta

---

src/templates/inventario/entrada/imprimir_qr.html
src/templates/inventario/salida/tpe_print.html

- Se realizo pruebas de impresion de qr
- Se modifico el template de qr para poder imprimir 
***

Pruebas de impresion

---

src/apps/inventario/admin.py
src/apps/inventario/models.py
src/apps/inventario/serializers/bodega.py
src/src/settings.py

Cambios en Admin e impresion de QR

---

src/apps/escuela/models.py
src/src/settings.py

Correcciion matricula de escuela

---

src/apps/inventario/views/dispositivo.py
src/static/js/extrajs/inventario.js

limpieza de codigo

---

src/apps/inventario/api_views/repuesto.py
src/apps/inventario/forms/dispositivo.py
src/apps/inventario/forms/repuesto.py
src/apps/inventario/menus.py
src/apps/inventario/serializers/bodega.py
src/apps/inventario/urls/repuesto.py
src/apps/inventario/views/dispositivo.py
src/apps/inventario/views/entrada.py
src/apps/inventario/views/repuesto.py
src/static/js/extrajs/inventario.js
src/templates/inventario/repuesto/imprimir_qr_list.html
src/templates/inventario/repuesto/repuesto_list.html
src/templates/inventario/repuesto/repuesto_print.html

- Se ordenaron los accesos en el menu principal
- Se arreglaron los marges para la impresion de los qr de repuesto
***

Correcion en la impresion de QR de repuestos y menus en general

---

src/apps/inventario/admin.py
src/apps/inventario/menus.py
src/src/settings.py
src/templates/inventario/admin/dispositivo_changelist.html
src/templates/inventario/admin/salidainventario_changelist.html

Subir Data Admin

---

src/apps/inventario/menus.py
src/templates/inventario/dispositivo/asignaciontecnico_list.html

Correccion de menus

---

src/apps/inventario/forms/salida.py
src/apps/inventario/models.py
src/src/settings.py
src/static/js/extrajs/inventario.js
src/templates/inventario/repuesto/repuesto_list.html
src/templates/inventario/salida/salida_add.html

Correccion de informe de repuestos

---

src/apps/conta/api_urls.py
src/apps/conta/forms.py
src/apps/conta/urls.py
src/apps/conta/views.py
src/apps/inventario/models.py
src/src/settings.py
src/static/js/extrajs/conta.js
src/static/js/extrajs/inventario.js
src/templates/base/base.html
src/templates/conta/informe_desecho.html
src/templates/conta/informe_resumen.html
src/templates/conta/informe_salidas.html
src/templates/inventario/dispositivo/ap/ap_edit.html
src/templates/inventario/entrada/entrada_edit.html

- Reporte de Entradas a Inventario
- Reporte de Salidas de Inventario
- Reporte de Desecho
- Resumen de Inventario
***

Reportes de Contabilidad

---

src/apps/inventario/api_views/entrada.py
src/apps/inventario/forms/entrada.py
src/apps/inventario/serializers/entrada.py
src/apps/inventario/urls/desecho.py
src/apps/inventario/views/desecho.py
src/static/js/extrajs/inventario.js
src/templates/inventario/desecho/desechosalida_add.html

Desecho Pendiente y correccion en Entradas

---

src/apps/inventario/serializers/entrada.py
src/apps/inventario/views/salida.py

- Correccion de errores al momento de crear una entrada
***

correccion en serializacion de entradas

---

src/apps/inventario/api_views/dispositivo.py
src/apps/inventario/views/salida.py
src/src/settings.py
src/static/js/extrajs/inventario.js
src/templates/inventario/dispositivo/solicitudmovimiento_update.html
src/templates/inventario/salida/garantia_print.html
src/templates/inventario/salida/revisionsalida_update.html
src/templates/inventario/salida/tpe_print.html

Lectura de QR de contabilidad y mejroas al formato de entregas

---

src/apps/inventario/api_views/dispositivo.py
src/apps/inventario/serializers/salida.py
src/apps/inventario/views/salida.py
src/src/settings.py
src/static/js/extrajs/inventario.js
src/templates/inventario/salida/garantia_print.html
src/templates/inventario/salida/revisionsalida_list.html
src/templates/inventario/salida/revisionsalida_update.html

Correccion de Revisiones

---

src/templates/inventario/salida/tpe_print.html

Cambios en Informe de TPE

---

src/apps/inventario/views/salida.py
src/src/settings.py
src/templates/inventario/salida/tpe_print.html

Mejoras de Reporte TPE

---

src/apps/inventario/views/salida.py
src/src/settings.py
src/templates/inventario/salida/tpe_print.html

 Mejoras de Reporte TPE

---

src/apps/inventario/menus.py
src/apps/inventario/models.py
src/static/js/extrajs/inventario.js

Asignacion de Tecnicos a Informes

---

.gitignore
src/apps/inventario/api_views/dispositivo.py
src/apps/inventario/api_views/entrada.py
src/apps/naat/views.py
src/static/js/extrajs/inventario.js
src/templates/inventario/dispositivo/dispositivos_list.html

- Se cambio el nombre a una variable de jquery en el html para que no mostrar un error
***

se corrigio un error en los listados de dispositivos

---

src/apps/mye/serializers.py
src/static/js/extrajs/mye.js
src/templates/mye/solicitud_list.html

 Número de Solicitud

---

src/apps/inventario/api_views/dispositivo.py
src/apps/inventario/api_views/salida.py

- Creacion de punto de acceso para tarimas
- Mejora al momento de consultar datos de dispositivo
***

Acceso de tarimas y mejoras al consultar datos

---

src/apps/inventario/api_views/entrada.py
src/apps/inventario/api_views/salida.py
src/apps/inventario/models.py
src/apps/inventario/views/entrada.py
src/apps/inventario/views/salida.py
src/static/js/extrajs/inventario.js
src/templates/inventario/salida/paquetes_detail.html

- Cambios en javascript de modulo de paquetes
- Cambio  en las entradas especiales
- Mejoras al momento de crear dispositivos
***

cambios en javascript,correcion de errores

---

src/apps/inventario/views/dispositivo.py
src/static/js/extrajs/inventario.js
src/templates/inventario/salida/paquetes_detail.html

- Cambio  de permiso en solicitud movimiento
***

permisos para movimiento de dispositivo

---

src/apps/inventario/api_views/dispositivo.py
src/apps/inventario/api_views/salida.py
src/static/js/extrajs/inventario.js
src/templates/inventario/salida/paquetes_detail.html

- Hacer mas rapido la respuesta  del servidor al momento de consultar un dispositivo
- Correccion de errores en el modulo de control de calidad
***

correccion en control de calidad y contabilidad 

---

src/apps/inventario/api_views/dispositivo.py
src/apps/inventario/api_views/salida.py
src/apps/inventario/views/dispositivo.py
src/static/js/extrajs/inventario.js
src/templates/inventario/salida/paquetes_detail.html

 correccion en control de calidad y contabilidad al momento de aprobar

---

src/apps/inventario/api_views/entrada.py
src/apps/inventario/api_views/salida.py
src/apps/inventario/forms/entrada.py
src/apps/inventario/models.py
src/apps/inventario/views/entrada.py
src/src/settings.py
src/static/js/extrajs/inventario.js
src/templates/inventario/entrada/constancia_entrada.html
src/templates/inventario/entrada/entrada_add.html
src/templates/inventario/entrada/entradadetalle_add.html
src/templates/inventario/entrada/informe_sucio.html

Mejoras de Entradas y Correcciones de Salidas

---

src/apps/inventario/menus.py
src/apps/inventario/views/entrada.py
src/templates/inventario/dispositivo/solicitudmovimiento_detail.html

- Se agrego permisos para  que control de calidad pueda trabajar en entradas
***

permisos asignados para control de calidad sobre entradas

---

src/apps/conta/views.py
src/apps/inventario/api_views/entrada.py
src/apps/inventario/api_views/salida.py
src/apps/inventario/menus.py
src/apps/inventario/views/entrada.py
src/src/settings.py
src/static/js/extrajs/inventario.js
src/templates/inventario/entrada/entradadetalle_dispositivos.html

- Primer Paquete de mejoras para el módulo de entradas en General
- Quitar un día a la fecha inicial de los informes de inventario.
- Adjuntar Desecho a las salidas del resumen
- Permisos de conta y cc a los menús. 
***

Mejoras de Entradas y Correcciones generales

---

src/apps/conta/views.py
src/apps/inventario/api_views/entrada.py
src/apps/inventario/menus.py
src/apps/inventario/views/entrada.py
src/src/settings.py
src/static/js/extrajs/inventario.js
src/templates/inventario/entrada/entrada_detail.html
src/templates/inventario/entrada/entrada_edit.html

- Eliminar Prints
- Desactivar impresión de dispositivos en la entrada
- Mejoras de seguridad para bodega, cc y técnicos en entradas. 
***

Correcciones de Entradas y Mejoras en la Seguridad

---

src/apps/inventario/api_views/dispositivo.py
src/apps/inventario/api_views/salida.py
src/templates/inventario/dispositivo/solicitudmovimiento_detail.html
src/templates/inventario/salida/paquetes_detail.html
src/templates/inventario/salida/tpe_print.html

- Corrección de las observaciones en solictudes - kardex
- Correccion en informe de entrega de TPE
- Correccion al aprobar dispositivos tipo Switch en CC y Conta
***

 Correccion de Errorres en distintos modulos

---

src/apps/inventario/api_views/dispositivo.py
src/static/js/data/dispositivo.js

- Se arreglo un error al momento de seleccionar los campos checkbox 
- Limpieza de codigo en el archivo javascript de el grid
***

correccion de errores en campo booleano

---

src/apps/conta/views.py
src/apps/inventario/views/salida.py
src/src/settings.py
src/templates/inventario/salida/garantia_print.html

- Corrección del saldo inicial de informes 
- Permisos de vistas a bodega
- Cambio en la carta de garantía para escuelas de Visión Mundial
***

Verificar la fecha inicial de Informes

---

src/templates/base/base.html
src/templates/inventario/dispositivo/ap/ap_detail.html
src/templates/inventario/dispositivo/ap/ap_edit.html
src/templates/inventario/dispositivo/cpu/cpu_detail.html
src/templates/inventario/dispositivo/cpu/cpu_edit.html
src/templates/inventario/dispositivo/hdd/hdd_detail.html
src/templates/inventario/dispositivo/hdd/hdd_edit.html
src/templates/inventario/dispositivo/laptop/laptop_detail.html
src/templates/inventario/dispositivo/laptop/laptop_edit.html
src/templates/inventario/dispositivo/monitor/monitor_detail.html
src/templates/inventario/dispositivo/monitor/monitor_edit.html
src/templates/inventario/dispositivo/mouse/mouse_detail.html
src/templates/inventario/dispositivo/mouse/mouse_edit.html
src/templates/inventario/dispositivo/red/red_detail.html
src/templates/inventario/dispositivo/red/red_edit.html
src/templates/inventario/dispositivo/tablet/tablet_detail.html
src/templates/inventario/dispositivo/tablet/tablet_edit.html
src/templates/inventario/dispositivo/teclado/teclado_detail.html
src/templates/inventario/dispositivo/teclado/teclado_form.html
src/templates/inventario/salida/dispositivos_grid_paquetes.html

- Cambio  el grid de paquetes y dispositivos
- Cambio en la edicion de dispositivos
***

correccion de errores

---

src/apps/conta/forms.py
src/apps/conta/views.py

Resolución de Mejoras de Informes

---

src/templates/inventario/salida/salida_edit.html

correccion de paquetes

---

src/apps/inventario/api_views/desecho.py
src/apps/inventario/api_views/dispositivo.py
src/apps/inventario/forms/desecho.py
src/apps/inventario/serializers/bodega.py
src/apps/inventario/views/salida.py
src/static/js/extrajs/inventario.js
src/templates/inventario/desecho/desechosalida_add.html
src/templates/inventario/desecho/desechosalida_form.html
src/templates/inventario/desecho/desechosalida_list.html

Reparación de Errores

---

src/apps/certificado/views.py

- Correccion en la url del certificado
***

correcion  a la hora de crear certificados

---

src/apps/cyd/forms.py
src/apps/cyd/urls.py

Corrección
- Cambio 1
- Cambio 2
***

Error en SUNI

---

src/apps/Bienestar/forms.py
src/apps/Bienestar/menus.py
src/apps/Bienestar/urls.py
src/apps/Bienestar/views.py
src/static/js/extrajs/bienestar.js
src/templates/bienestar/bienestar_informe.html

- Se  arreglo el menu
- Se separo el formulario de busqueda del acordeon
- Ahora carga los datos al inicio
- Se hizo obligatorio poner el nombre del colaborador
***

cambios en bienestar

---

src/apps/informe/urls.py
src/apps/informe/views.py
src/static/js/extrajs/informe.js
src/templates/informe/informe.html

- Actualizacion del modulo de informes
***

Actualizacion de informe

---

src/apps/controlNotas/views.py
src/apps/escuela/views.py
src/templates/controlNotas/registros.html

correccion  en template de registros

---

src/apps/controlNotas/views.py
src/templates/controlNotas/registros.html

-  Se corrigió un error en la tablas de alumnos
***

correcion en tabla de estudiantes

---

.gitignore
src/apps/Bienestar/views.py
src/apps/inventario/api_views/entrada.py
src/apps/inventario/views/dispositivo.py
src/static/js/extrajs/bienestar.js
src/static/js/extrajs/inventario.js
src/templates/bienestar/bienestar_informe.html

Conjunto de cambios para módulo de inventario y bienestar.
- Cambio 1
- Cambio 2
***

Cambios Módulos Inventario y Bienestar

---

.gitignore
src/apps/certificado/views.py
src/apps/cyd/views.py
src/apps/escuela/models.py

Cambios menores en el módulo de certificados y escuelas. Se agregaron validaciones en algunos filtros y se cambió la periodicidad de los datos para descargar certificados.
***

Módulo certificado / escuelas

---

src/apps/cyd/models.py
src/apps/inventario/api_views/dispositivo.py
src/apps/inventario/api_views/interno.py
src/apps/inventario/forms/dispositivo.py
src/apps/inventario/forms/entrada.py
src/apps/inventario/models.py
src/apps/inventario/serializers/bodega.py
src/apps/inventario/serializers/entrada.py
src/apps/inventario/serializers/interno.py
src/static/js/extrajs/inventario.js
src/templates/inventario/dispositivo/dispositivos_list.html
src/templates/inventario/dispositivo/solicitudmovimiento_detail.html
src/templates/inventario/dispositivo/solicitudmovimiento_update.html
src/templates/inventario/salida/tpe_print.html
src/templates/kardex/salida_print.html

- Cambios en informes de tpe
- Actualizacion de codigo
***

Requerimientos  buen viaje arnold

---

src/templates/inventario/desecho/desecho_print.html

- Se agrego el peso total a los reportes de desecho
***

actualizacion en reporte de desecho

---

src/templates/inventario/desecho/desecho_print.html

Reverts jinchuika/app-suni#370

Revert "actualizacion en reporte de desecho"

---

src/apps/conta/views.py

- Correcciones en los informes de contabilidad en especifico del Resumen para obtener los datos de el precio de los lotes
***

Corrección en informe de contabilidad enero 2023

---

src/apps/conta/views.py

Reverts jinchuika/app-suni#373

Revert "Corrección en informe de contabilidad enero 2023"

---

src/apps/conta/views.py

Reverts jinchuika/app-suni#375

Revert "Revert "Corrección en informe de contabilidad enero 2023""

---

src/apps/conta/views.py

Reverts jinchuika/app-suni#377

Revert "Revert "Revert "Corrección en informe de contabilidad enero 2023"""

---

src/apps/conta/views.py

- Se corrigio los cambios en el informe de desecho
***

correcciones en  salidas de desecho

---

src/apps/conta/views.py

- Cambio en informes de contabilidad
***

correccion en informe contabilidad

---

src/apps/beqt/api_views/salida.py
src/apps/beqt/views/salida.py
src/templates/beqt/salida/garantia_print.html

Cambios en Beqt

---

src/apps/inventario/forms/entrada.py

- Correccion en los decimales de  detalles de entrada
***

Correccion en decimales de contabilidad

---

src/apps/beqt/api_views/salida.py
src/apps/beqt/views/salida.py
src/apps/inventario/views/entrada.py
src/apps/inventario/views/salida.py
src/apps/tpe/serializers.py
src/static/js/extrajs/beqt.js
src/templates/beqt/salida/garantia_print.html
src/templates/beqt/salida/laptop_print.html
src/templates/beqt/salida/salida_edit.html
src/templates/beqt/salida/tpe_beqt_print.html
src/templates/inventario/entrada/entrada_detail.html
src/templates/inventario/salida/salida_detail.html

- Cambio para corrección para mostrar números de teléfono en las cartas de entrega BEQT 
***

Cambios de BEQT

---

src/static/js/extrajs/inventario.js
src/templates/inventario/entrada/entrada_detail.html

-  Se agrego  el proyecto en el detalle 
***

mostrar proyecto en detalle de entrada

---

src/apps/escuela/views.py

- control del error al momento de que no tiene sede
***

Error al momento de mostrar escuela que no tiene sedes

---

src/apps/variasApis/urls.py
src/apps/variasApis/views.py
src/static/js/extrajs/cyd.js

- Cambio en los apis
- Cambio en el extrasjs de cyd
***

cambios en apis

---

src/apps/beqt/serializers/bodega.py

**- Cambio 1:** Modificación para que se pueda utilizar el escáner con las regletas de BEQT
***

Regletas de BEQT

---

src/apps/beqt/serializers/bodega.py
src/static/js/extrajs/cyd.js
src/templates/cyd/sede_list.html

- Se valido que cuando se ingresa participantes por listado no se pueda guardar el listado hasta que todos los dpi sean validos
- Control de calidad de las regletas de beqt con el lector de QR
***

Validar participante en cyp y control de calidad beqt

---

src/apps/cyd/models.py

- Cambios en el modelo de cyp
***

actualizacion de modelo de cyp

---

src/apps/variasApis/urls.py
src/apps/variasApis/views.py

- Control de calidad a los reportes al  incluir nueva imagen de BEQT
- Control de calidad  al modulo de tpe en la funcion de equipamiento para poder ingresar el numero de referencia
***

Cambios en varias apis y control de calidad  a beqt, tpe 

---

src/apps/conta/creacion_filtros_informe.py
src/apps/conta/forms.py
src/apps/conta/urls.py
src/apps/conta/views.py
src/apps/inventario/menus.py
src/static/js/extrajs/conta.js
src/templates/conta/informe_existencia_dispositivos.html

- Creacion de informe de existencia de dispositivos
***

Informe de existencia contabilidad

---

src/apps/conta/forms.py
src/apps/conta/views.py

- Se actualizo el campo de dispositivo para que sea de seleccion multiple
- Se actualizo la forma de manajer las fechas
***

Cambios en informe de existencia

---

src/apps/cyd/menus.py
src/apps/cyd/views.py
src/static/js/extrajs/cyd.js
src/templates/cyd/InformeEscuelaListado.html
src/templates/cyd/sede_list.html

- Se agregaron nuevas columnas al informe por listado de escuela
- Se agrego en los filtros de sede que solo aparescan las activas
***

Cambios en informe cyd y filtros de sedes activas

---

src/apps/conta/views.py
src/apps/inventario/views/salida.py
src/templates/inventario/salida/dispositivos_salida.html

- Cambio en el informe de existencia de contabilidad
- Cambio dispositivos en paquete ahora contabilidad puede ver precio de cada dispositivo
***

cambios en informe de existencias y precios de dispositivos en paquetes

---

src/apps/conta/views.py
src/static/js/extrajs/conta.js

- Cambio en la vista de informe de existencia  para obtener bien el precio del dispositivo
- Cambio en javascript para darle formato de miles
***

correcciones en informe de existencia

---

src/apps/beqt/models.py
src/apps/beqt/views/salida.py

- Se modifico para que tome el último director que fue ingresado de la escuela donde se va a ser la entrega.
***

Carta Laptop BEQT

---

src/apps/inventario/views/salida.py

- Correcion en la asignacion de dispositivos a paquetes
***

correccion en errores de asignacion paquete

---

src/apps/conta/forms.py
src/apps/conta/urls.py
src/apps/conta/views.py
src/apps/inventario/api_views/salida.py
src/apps/inventario/menus.py
src/apps/inventario/models.py
src/static/js/extrajs/conta.js
src/static/js/extrajs/inventario.js
src/templates/conta/informe_rastreo_desecho.html

- Creacion de  informe sobre el rastreo de desecho
- Cambios al momento de listar las entregas ahora solo muestra al inicio las que estan en creacion con los filtros se podran encontrar las demas entregas
***

informe rastreo de desecho

---

src/templates/inventario/salida/salida_add.html

- Se agrego el template html para optimizacion de salidas
***

optimizacion de listado de salidas

---

src/apps/conta/forms.py
src/apps/conta/urls.py
src/apps/conta/views.py
src/apps/inventario/menus.py
src/static/js/extrajs/conta.js
src/templates/conta/informe_rastreo_repuesto.html

- Informe de repuestos
- Permisos para que el admin de inventario vea los informes
***

informe de repuesto y permisos para admin

---

src/apps/conta/forms.py
src/apps/conta/urls.py
src/apps/conta/views.py
src/apps/inventario/menus.py
src/static/js/extrajs/conta.js
src/templates/conta/informe_rastreo_repuesto.html
src/templates/inventario/salida/salida_add.html

informe de repuesto y permisos para admin #448 

---

src/static/js/extrajs/conta.js

- Se cambio el tamanio de la pagina y la orientacion al momento de exportar los informes en pdf
***

cambio en la orientacion y tamanio de exportacion

---

src/apps/beqt/api_views/dispositivo.py
src/apps/beqt/api_views/entrada.py
src/apps/beqt/api_views/salida.py
src/apps/beqt/forms/dispositivo.py
src/apps/beqt/models.py
src/apps/beqt/urls/dispositivo.py
src/apps/beqt/views/dispositivo.py
src/apps/beqt/views/salida.py
src/apps/inventario/forms/dispositivo.py
src/apps/inventario/serializers/bodega.py
src/apps/inventario/views/salida.py
src/static/js/data/dispositivo.js
src/static/js/data/paquetes.js
src/static/js/extrajs/inventario.js
src/templates/beqt/salida/dispositivos_grid_paquetes.html
src/templates/beqt/salida/tablet_print.html
src/templates/inventario/dispositivo/dispositivos_list.html
src/templates/inventario/salida/garantia_print.html
src/templates/inventario/salida/laptop_print.html
src/templates/inventario/salida/tpe_print.html

- Cambios TPE:
Se muestran los purtos de los mouse y teclados en el listado de dispositivos Se cambio la hoja de entrega de Laptops
- Cambio BEQT:
Se agrego dispositivo protector de tablet
***

Cambios BEQT y TPE v2

---

src/apps/beqt/api_views/dispositivo.py
src/apps/beqt/api_views/entrada.py
src/apps/beqt/api_views/salida.py
src/apps/beqt/models.py
src/apps/beqt/urls/dispositivo.py
src/apps/beqt/views/salida.py
src/apps/inventario/serializers/bodega.py
src/apps/inventario/views/salida.py
src/static/js/data/dispositivo.js
src/static/js/data/paquetes.js
src/templates/beqt/salida/tablet_print.html
src/templates/inventario/dispositivo/dispositivos_list.html
src/templates/inventario/salida/garantia_print.html
src/templates/inventario/salida/laptop_print.html
src/templates/inventario/salida/tpe_print.html

- Cambios TPE:
Se muestran los puertos de los mouse y teclados en el listado de dispositivos
Se cambio la hoja de entrega de Laptops
- Cambio BEQT:
Se agrego dispositivo protector de tablet
***

Cambios TPE y Protectores BEQT

---

src/apps/certificado/views.py
src/apps/cyd/views.py
src/static/js/extrajs/cyd.js
src/templates/cyd/InformeParticipanteCapacitador.html

- Cambio en  cyp
- Cambio en certificados
***

correccion de errores en cyp y certificados

---

src/apps/certificado/views.py
src/static/js/extrajs/cyd.js
src/templates/cyd/sede_detail.html

- Actualizacion de certificados en el modulo de certificados
- Grafica de promocion en cyp
***

actualizacion de certificados y grafica de promocion

---

src/apps/inventario/forms/salida.py

- Se valido en la creacion de reviciones de contabilidad para que solo aparescan las salidas que estan en desarrollo
***

validacion en revicion de contabilidad

---

src/apps/variasApis/urls.py
src/apps/variasApis/views.py

Migración de datos de CYP
- Cambios al modulo de varias apis (View, url) 
***

Ajustes a Migración CYP

---

src/apps/certificado/views.py

- Se actualizacion las validaciones para el certificado de naat
***

Actualizacion en validacion de naat

---

src/apps/certificado/views.py

- Se implemento la descarga del certificado de Kolibri-Khan Academy con TNI
***

Actualizacion de certificado de Kolibri-Khan y TNI

---

src/apps/Evaluacion/forms.py
src/apps/Evaluacion/views.py
src/templates/Evaluacion/formulario_detail.html
src/templates/base/base.html

Cambios por perdida de paquetes en asignaciones
Cambios en conteo de asignaciones en evaluacion detail
Cambio en el `base.html` para fecha de copyright 
***

Cambios y mejoras Evaluación

---

src/apps/cyd/models.py
src/apps/cyd/views.py
src/static/js/extrajs/cyd.js
src/templates/cyd/InformeCapacitadores.html
src/templates/cyd/sede_detail.html

- Se agrego al informe por capacitador cuantas escuelas invitadas tiene y el numero de participantes
***

personas invitadas en informes y listado

---

src/apps/cyd/models.py
src/apps/cyd/views.py
src/static/js/extrajs/cyd.js
src/templates/cyd/InformeCapacitadores.html
src/templates/cyd/sede_detail.html

- Actulizacion de numero de escuelas invitadas y participantes invitados en informes y listados
***

Personas invitadas en informes y listado cyp

---

src/apps/inventario/api_views/dispositivo.py

- Cambios en el api views de inventario, para conectarse a la app de inventario
***

Cambios de Api inventario

---

src/apps/users/views.py
src/src/settings.py
src/templates/users/perfil.html

- Se añadio la tabla para crear tokens (necesita migración en manage.py) 
- Se añadio la autenticación de tokens para apis
- Se añade el apartado para generar QR de los tokens en el perfil del usuario.
***
***

Tokens para Rest Framework

---

src/apps/cyd/models.py
src/apps/users/views.py
src/src/settings.py
src/templates/users/perfil.html

- Autentificacion con tokens
- Qr de token en perfil
***
***

Tokens rest framework

---

src/apps/inventario/api_views/dispositivo.py

- Uso de TokenAuthentication en api para pasar token en el header de la api `DispositivoViewSet`
***

TokenAuthentication

---

src/apps/conta/views.py

##
Actualización de código de Vista Planilla.

Actualización de Vista Planilla

---

src/apps/cyd/forms.py
src/apps/cyd/menus.py
src/apps/cyd/urls.py
src/static/js/extrajs/cyd.js
src/templates/cyd/InformeSoloParticipante.html

- Creacion de informe por participantes
***

informe por parcipante

---

src/apps/cyd/views.py

Actualizacion de view.py

---

src/apps/cyd/views.py

- Cambio en view.py  de cyp
***

Actualizacion de view.py de cyp

---

src/apps/cyd/views.py

- Correccion de error al momento de enviar donante en informe cyd
***

Actualizacion de donante
